### ISSUE TITLE
Agenda for Nov 13, 2024

### ISSUE THREAD

**Issue by amitkaps** [vizchitra/notes#3]
Meeting led by: @Ipsa

Meeting Agenda

- Build Momentum (Amit)
  - 2 Milestones & 6 Workstreams
  - Small teams 5-6 members per stream
  - Asynchronous collaboration - Github Issues
  - [Vizchitra Notes WebSite](https://vizchitra.com/notes/)
- Walkthrough to the Workstreams (Ipsa & Apoorv)
  - Details about each work stream scope
  - 2 tasks to be done for each stream
- Members list and Workstream choices
- Brand exercise by @hamsa and @rasagy

**Comment by apoorv74** [comment]
Attendees:
1. amit
3. karan
4. swathi
5. kashvi
6. hamsa
7. ipsa
8. rasagy
9. apoorv
10. kavya
11. anand
12. schubert

Notes:
1. Date fixed for the conference (April 26th, 2024). Need to align on the scale of the conference. A mini-conf might be a bit more manageable. 
2. Two deadlines - First to launch the community (**Jan 7th**). Second is the conference day (**April 26th**).
3. Six workstreams - So people can get involved and drive these. 5-6 members in each to start with. How can we work asynchronously. Using `Github issues` is one option. 
4. The bi-weekly meeting should be to take decisions. 
5. [Github pages](https://vizchitra.com/notes/) is deployed. One person per team should be able to update this on Github for public viewing.
6. Will it be helpful to assign a 'day' for async updates from each stream? E.g. Tuesday for Admin and Brand, Wed for Comms and editorial, Thurs for Events & Partnerships
7. Rasagy - Website Creation - Check with Zainab - If some/any assets can be re-used or build from scratch
8. One page website for community engagement vs full website for managing the conference. 
9. Align work for Branding and Comms because we are working on a tight deadline
10. Assign people to workstreams. Update the [members/streams](https://docs.google.com/spreadsheets/d/1Vfxe6mashH19zObWQ74mYwXr_ftUNzsOO5FUFaP8w0Q/edit?gid=1435564915#gid=1435564915) worksheet
11. Collaborative exercise - Branding Discussion - Figuring out core of this group. Objective is to articulate who we are are who we aren't, what we do, what we speak, etc. Rasagy and Hamsa will synthsize and articulate the responses shared on chat.
12. For the next discussion - Will be good to get updates from each stream.

**Comment by amitkaps** [comment]
Thanks @apoorv74 for the same. Added meeting notes to the page - https://vizchitra.com/notes/meeting/20241113.html

@gurman let me know when you have the transcript doc and video link, will add the same.

**Comment by amitkaps** [comment]
Added links to meeting video, auto transcript and chat conversation
